import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./styles.module.css";

const myArray = [
  "circle",
  "x-shape",
  "circle",
  "x-shape",
  "circle",
  "x-shape",
  "circle",
  "x-shape",
  "circle",
  "x-shape",
  "circle",
  "x-shape",
  "circle",
  "x-shape",
  "circle",
  "x-shape",
  "circle",
  "x-shape",
  "circle",
  "x-shape",
  "circle",
  "x-shape",
  "circle",
  "x-shape",
];

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.lines}>
          <div className={styles.line1}>
            <div className={styles.shapes}>
              {myArray.map((shape, index) => (
                <div key={index} className={`${styles[shape]}`}></div>
              ))}
            </div>
          </div>
          <div className={styles.line2}>
            <div className={styles.shapes}>
              {myArray.map((shape, index) => (
                <div key={index} className={`${styles[shape]}`}></div>
              ))}
            </div>
          </div>
          <div className={styles.line3}>
            <div className={styles.shapes}>
              {myArray.map((shape, index) => (
                <div key={index} className={`${styles[shape]}`}></div>
              ))}
            </div>
          </div>
          <div className={styles.line4}>
            <div className={styles.shapes}>
              {myArray.map((shape, index) => (
                <div key={index} className={`${styles[shape]}`}></div>
              ))}
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
